### ISSUE TITLE
New Accelerate ILP64 does not compile: lapack_int (long) vs int64_t (long long) in the ILP64 alias paths

### ISSUE THREAD

**Issue by mmelnich** [icl-utk-edu/lapackpp#89]
## Reproduce

On macOS >= 13.3, against a BLAS++ built with `-Dblas=accelerate -Dblas_int=int64` (which selects the new interface with `BLAS_ILP64`, per icl-utk-edu/blaspp#134):

```
cmake -S lapackpp -B build -Dblaspp_DIR=<...>/lib/cmake/blaspp -Dbuild_tests=OFF
cmake --build build
```

Configure succeeds (LAPACK 3.12.00 detected), the build fails at the first wrapper that aliases an integer array:

```
src/gbcon.cc:37:27: error: cannot initialize a variable of type 'const lapack_int *'
(aka 'const long *') with an lvalue of type 'const int64_t *' (aka 'const long long *')
        lapack_int const* ipiv_ptr = ipiv;
```

## Cause

`include/lapack/config.h` deliberately typedefs `lapack_int` to `long` under `LAPACK_ILP64` + `ACCELERATE_NEW_LAPACK`, to match Apple's `__LAPACK_int` (the comment there notes it is a distinct type from `int64_t` == `long long` on Darwin). But the wrappers' ILP64 no-copy paths assume `lapack_int` and `int64_t` are the same type:

```cpp
#ifndef LAPACK_ILP64
    std::vector<lapack_int> ipiv_( &ipiv[0], &ipiv[(n)] );
    lapack_int const* ipiv_ptr = &ipiv_[0];
#else
    lapack_int const* ipiv_ptr = ipiv;   // ill-formed when lapack_int is long
#endif
```

So the combination introduced by #88 compiles for LP64 Accelerate but not for ILP64 Accelerate; #88's CI had no macOS ILP64 lane, which is why it went unseen. (LP64 Accelerate is unaffected, and BLAS++ itself is unaffected because its integer arguments pass by value.)

## Possible directions

1. Take the copy path whenever `lapack_int` is not the same type as `int64_t` (the copy branch already compiles for any integer conversion), e.g. gate the alias on `std::is_same<lapack_int, int64_t>` or an `LAPACK_ILP64_IS_INT64` config macro rather than on `LAPACK_ILP64` alone. Mechanical, but touches every wrapper with an integer-array argument.
2. Keep `typedef int64_t lapack_int` for ILP64 Accelerate as well: `long` and `long long` have the same representation on Darwin, and the wrappers call through extern-C prototypes, so the ABI is unchanged; only code that includes Apple's own LAPACK prototypes alongside would need a cast at that boundary.

Happy to prepare a PR for whichever direction you prefer.

**Comment by mgates3** [comment]
I don't quite follow your suggestion (2). Can you give a code snippet to show what you mean?

With a static assert to ensure that int64_t and lapack_int are the same size, can we do a cast there? E.g.,
```
    static_assert( sizeof( lapack_int ) == sizeof( int64_t ) );
    lapack_int const* ipiv_ptr = (lapack_int*) ipiv;
```
Generally I've dealt with data type issues by putting casts in the wrappers, so the BLAS++/LAPACK++ API uses standard types (int64_t, std::complex, etc.).

**Comment by mmelnich** [comment]
On (2): what I meant was keeping `typedef int64_t lapack_int` even for ILP64 Accelerate,

```cpp
#if defined(LAPACK_ILP64)
    typedef int64_t lapack_int;   // Accelerate or not
#else
    typedef int lapack_int;
#endif
```

relying on `long` and `long long` having the same representation across the extern-C boundary. I checked it against the tree and withdraw it: `fortran.h` includes Apple's own prototypes from `Accelerate.h` under `ACCELERATE_NEW_LAPACK` (which is the right design — that is what got the const-ness questions settled in #88), and those take `__LAPACK_int* == long*`, so with `lapack_int = int64_t` the same type error just reappears at every call of Apple's prototypes. `lapack_int` has to stay `long` there.

Your approach is the correct one, and it matches how blaspp already behaves: `blas_int` is also `long` in this configuration and compiles fine because its integers pass by value; the pointer aliasing is what breaks, and casts at those sites keep the public API on `int64_t` as you describe. PR: #90. It applies the cast at each of the 356 ILP64 alias sites (const-ness preserved) and puts a single `static_assert( sizeof(lapack_int) == sizeof(int64_t) )` in `config.h` rather than one per site. Verified by simulating the long/long-long split on Linux: unpatched fails exactly as reported at `gbcon.cc:37`, patched builds the full library.
